CLASS zbp_i_online_shop_45 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_online_shop_45.

  PUBLIC SECTION.
    CLASS-DATA cv_pr_mapped TYPE RESPONSE FOR MAPPED
    i_purchaserequisitiontp.

    CLASS-DATA cv_po_mapped TYPE RESPONSE FOR MAPPED i_purchaseOrderTP_2.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_i_online_shop_45 IMPLEMENTATION.
ENDCLASS.
